added the bottom bar and change the icon of header
Bridgeconn/VachanOnline-v2 pull request #249
Opened 2022-12-05 11:42 UTC by Poojanavgurukul

2023-02-08 10:55 UTC, AnuMonachan commented on src/components/Drawer/Drawer.js
> +            title="infographics"
Capitalize title

2023-02-08 10:56 UTC, AnuMonachan commented on src/components/common/BookCombo.js
> +        className="ke"
extra className

2023-02-08 10:57 UTC, AnuMonachan commented on src/components/read/BiblePane.js
> +
extra spaces can be removed if they are coming as changes

2023-02-08 10:58 UTC, AnuMonachan commented on src/components/read/TopBar.js
> +
extra spaces between imports can be removed

2023-02-08 10:59 UTC, AnuMonachan commented on src/store/reducer.js
> +      // let { bookCode, chapter } = state.panel1;
comment can be removed if not required

2023-02-08 11:06 UTC, AnuMonachan commented
UI Changes required -

- Commentary bookcombo retaining language from bible.
- Change parallel scroll icon position
- Metadata icon getting hidden from top bible pane when we switch to parallel bible

2023-04-14 10:49 UTC, RevantCI commented
- Commentary dropdown only showing 3 letters show full commentary code eg ESVGSB shows ESV only. and Show upper case eg Hin is showing now

2023-04-14 10:51 UTC, RevantCI commented on src/index.css
> -
If possible try to add the css in the file that it is used in as colocations help in identifying if the class is used or not

2023-04-17 11:58 UTC, RevantCI requested changes

2023-04-17 11:58 UTC, RevantCI commented on src/components/common/BookCombo.js
> +  const styleProps = {
style props is not used, it can be removed

2023-04-17 11:58 UTC, RevantCI commented on src/components/common/BookCombo.js
> +    mobileView: state.local.mobileView,
This can be removed for now, later the code can be refactored and use mobileView from redux insted of passing minimal from parent props

2023-04-17 12:20 UTC, RevantCI commented on src/components/common/Version.js
> +    } else if (mobileView) {
Mobile and mobile View are the same both are xs only, the else if may not be required

2023-04-18 09:15 UTC, RevantCI commented on src/components/dictionary/Dictionary.js
> +      top: 145,
```suggestion
      top: 115,
      left: 20,
```

2023-04-18 09:16 UTC, RevantCI commented on src/components/dictionary/Dictionary.js
> +  textBox: {
textBox is not used so it can be removed here and below as well

2023-04-19 09:10 UTC, RevantCI requested changes

2023-04-19 09:47 UTC, RevantCI commented on src/components/read/ReadBible.js
> +  const [selectedVerses, setSelectedVerses] = React.useState([]);
This can be put in side bible pane1 and 2 as before, it should be indpendent on each pane and also no need to pass it to each bible pane

2023-04-19 11:00 UTC, Poojanavgurukul commented on src/components/dictionary/DictionaryWordCombo.js
>        marginRight: 10,
this not working it showing different changes  required

2023-04-19 11:06 UTC, Poojanavgurukul commented on src/components/dictionary/DictionaryWordCombo.js
> +      textOverflow: "ellipsis",
this changes not giving the desire output

2023-04-19 11:06 UTC, Poojanavgurukul commented on src/components/dictionary/DictionaryWordCombo.js
>        marginRight: 10,
this changes not giving the desire output

2023-04-20 05:10 UTC, Poojanavgurukul commented on src/components/dictionary/DictionaryWordCombo.js
>        marginRight: 10,
this is not working as we want

2023-04-25 13:25 UTC, RevantCI reviewed
Most of the changes have been done. Modified PR target branch. 
Merging it to mobile_view#241 branch to do the remaining work. Will send a PR to dev from here with the remaining changes.

2023-04-25 13:55 UTC, merged