fixed Commentary mobile singe page view opens Genesis 1 on opening #351
Bridgeconn/VachanOnline-v2 pull request #360
Opened 2023-06-07 05:49 UTC by Poojanavgurukul

#351

2023-06-07 11:04 UTC, RevantCI requested changes
As discussed the bookList passed to BookCombo should be in the language of the commentary not the bible in pane 1.

2023-06-07 22:10 UTC, RevantCI approved these changes

2023-06-07 22:19 UTC, RevantCI commented
The issue can be fixed in BookCombo.js itself.
It is better not to use local variable ie let in component. As in some cases it may not work. See [Article](https://react.dev/learn/state-a-components-memory#when-a-regular-variable-isnt-enough). So its better to avoid it
We can discuss the changes at the next standup.

2023-06-08 06:03 UTC, Poojanavgurukul commented
as discussed fix is done in this pr #351

2023-06-08 06:04 UTC, merged