Added button for sharing the verse of the day from the landing page #570
Bridgeconn/VachanOnline-v2 pull request #576
Opened 2024-02-08 06:12 UTC by Beenamol

Added button for share the verse of the day from the landing page
 #570

2024-02-13 08:45 UTC, RevantCI commented on src/components/landing/Banner.js
>    heading: {
heading: {
    position: "absolute",
    top: 74,
    color: WHITE,
    fontWeight: 800,
    fontFamily: "Sans",
    fontSize: "1.2rem",
    textShadow: "1px 1px 2px " + BLACK,
    background: BLACK + "50",
    borderRadius: 10,
    padding: "4px 15px",
    [theme.breakpoints.down("sm")]: {
      top: 75,
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "1.1rem",
    },
  },

2024-02-13 08:46 UTC, RevantCI commented on src/components/landing/Banner.js
> +  },
```suggestion
       color: WHITE,
  },
  shareIcon: {
    color: WHITE,
    cursor: "pointer",
    textShadow: "1px 1px 2px " + BLACK,
    marginTop: -1,
    marginLeft: 8,
  },
```

2024-02-13 08:47 UTC, RevantCI commented on src/components/landing/Banner.js
> +          />
```suggestion
            className={classes.shareIcon}
```

2024-02-13 08:52 UTC, RevantCI commented on src/components/landing/Banner.js
>    heading: {
```suggestion
    heading: {
    position: "absolute",
    top: 72,
    color: WHITE,
    fontWeight: 800,
    fontFamily: "Sans",
    fontSize: "1.2rem",
    textShadow: "1px 1px 2px " + BLACK,
    background: BLACK + "50",
    borderRadius: 10,
    padding: "4px 15px",
    [theme.breakpoints.down("sm")]: {
      top: 70,
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "1.1rem",
    },
  },
```

2024-02-13 08:54 UTC, RevantCI requested changes
The icon style can be changed slightly as suggested in the review code
Also we can put the verse text and reference in the copy text area. 
We can make it a multi-line

2024-02-15 10:07 UTC, RevantCI approved these changes

2024-02-20 09:18 UTC, AnuMonachan approved these changes

2024-02-20 09:20 UTC, RevantCI approved these changes

2024-02-20 09:21 UTC, merged